# source: "https://www.youtube.com/watch?v=qMYlpMsWsBE"
source: "https://www.youtube.com/watch?v=6dp-bvQ7RWo"

# source: "https://www.youtube.com/watch?v=0IgonpX1jMg"
# source: "https://www.youtube.com/watch?v=rPxWUFTKgds"
source_type: "youtube" # webcam, file, youtube, ip_cam

# ROI Zones for counting
zones:
  zone1:
    camera_id: "CAM_001"
    street: "Av. Javier Prado"
    polygon:
      - [370, 560]
      - [813, 190]
      - [1215, 304]
      - [1076, 714]
      - [626, 716]
  zone2:
    camera_id: "CAM_002"
    street: "Av. Arequipa"
    polygon:
      - [100, 100]
      - [1180, 100]
      - [1180, 620]
      - [100, 620]
  zone3:
    camera_id: "CAM_003"
    street: "Av. Salaverry"
    polygon:
      - [100, 100]
      - [1180, 100]
      - [1180, 620]
      - [100, 620]
  zone4:
    camera_id: "CAM_004"
    street: "Av. Petit Thouars"
    polygon:
      - [100, 100]
      - [1180, 100]
      - [1180, 620]
      - [100, 620]

speed_estimation:
  enabled: true
  pixels_per_meter: 10.0

persistence:
  enabled: true
  type: "csv"
  interval_seconds: 60
  output_dir: "data/traffic_logs"

server:
  host: "0.0.0.0"
  port: 8000

# Performance tuning for latency and fluidity
performance:
  # Target resolution (lower = less latency, less bandwidth)
  target_width: 1280
  target_height: 720

  # OpenCV buffer size (1 = minimum latency, higher = smoother but more delay)
  opencv_buffer_size: 30

  # Frame processing
  detect_every_n_frames: 1 # Run YOLO detection every N frames

  # YouTube stream quality (affects download speed and latency)
  # Options: "worst", "best[height<=480]", "best[height<=720]", "best"
  youtube_format: "best"

  # Pipeline buffers
  frame_buffer_size: 30
  result_buffer_size: 30
  capture_buffer_size: 60
  target_fps: 30
  source_fps: 30

model:
  path: "yolo11n.pt"
  conf_threshold: 0.3

display: true
